# Generated by Django 3.0.14 on 2022-07-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220709_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='cart_image',
        ),
    ]
